language: generic
matrix:
  include:
    - name: Test
      env: COMMAND=test
    - name: Analyze
      env: COMMAND=analyze
os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
      - libstdc++6
      - curl
before_script:
  - git clone https://github.com/flutter/flutter.git -b master
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter $COMMAND
cache:
  directories:
    - $HOME/.pub-cache