package com.georgeci.moneysurfer.uikit.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import com.georgeci.moneysurfer.uikit.tokens.AppColors

internal val LightColorScheme = lightColorScheme(
    primary = AppColors.Primary,
    onPrimary = AppColors.OnPrimary,
    primaryContainer = AppColors.PrimaryContainer,
    onPrimaryContainer = AppColors.OnPrimaryContainer,
    secondary = AppColors.Secondary,
    onSecondary = AppColors.OnSecondary,
    secondaryContainer = AppColors.SecondaryContainer,
    onSecondaryContainer = AppColors.OnSecondaryContainer,
    tertiary = AppColors.Tertiary,
    onTertiary = AppColors.OnTertiary,
    tertiaryContainer = AppColors.TertiaryContainer,
    onTertiaryContainer = AppColors.OnTertiaryContainer,
    error = AppColors.Error,
    onError = AppColors.OnError,
    errorContainer = AppColors.ErrorContainer,
    onErrorContainer = AppColors.OnErrorContainer,
    background = AppColors.Background,
    onBackground = AppColors.OnBackground,
    surface = AppColors.Surface,
    onSurface = AppColors.OnSurface,
    surfaceVariant = AppColors.SurfaceVariant,
    onSurfaceVariant = AppColors.OnSurfaceVariant,
    surfaceTint = AppColors.SurfaceTint,
    surfaceContainerLowest = AppColors.SurfaceContainerLowest,
    surfaceContainerLow = AppColors.SurfaceContainerLow,
    surfaceContainer = AppColors.SurfaceContainer,
    surfaceContainerHigh = AppColors.SurfaceContainerHigh,
    surfaceContainerHighest = AppColors.SurfaceContainerHighest,
    surfaceBright = AppColors.SurfaceBright,
    surfaceDim = AppColors.SurfaceDim,
    outline = AppColors.Outline,
    outlineVariant = AppColors.OutlineVariant,
    inverseSurface = AppColors.InverseSurface,
    inverseOnSurface = AppColors.InverseOnSurface,
    inversePrimary = AppColors.InversePrimary,
    scrim = AppColors.Scrim,
)

internal val DarkColorScheme = darkColorScheme(
    primary = AppColors.Dark.Primary,
    onPrimary = AppColors.Dark.OnPrimary,
    primaryContainer = AppColors.Dark.PrimaryContainer,
    onPrimaryContainer = AppColors.Dark.OnPrimaryContainer,
    secondary = AppColors.Dark.Secondary,
    onSecondary = AppColors.Dark.OnSecondary,
    secondaryContainer = AppColors.Dark.SecondaryContainer,
    onSecondaryContainer = AppColors.Dark.OnSecondaryContainer,
    tertiary = AppColors.Dark.Tertiary,
    onTertiary = AppColors.Dark.OnTertiary,
    tertiaryContainer = AppColors.Dark.TertiaryContainer,
    onTertiaryContainer = AppColors.Dark.OnTertiaryContainer,
    error = AppColors.Dark.Error,
    onError = AppColors.Dark.OnError,
    errorContainer = AppColors.Dark.ErrorContainer,
    onErrorContainer = AppColors.Dark.OnErrorContainer,
    background = AppColors.Dark.Background,
    onBackground = AppColors.Dark.OnBackground,
    surface = AppColors.Dark.Surface,
    onSurface = AppColors.Dark.OnSurface,
    surfaceVariant = AppColors.Dark.SurfaceVariant,
    onSurfaceVariant = AppColors.Dark.OnSurfaceVariant,
    surfaceTint = AppColors.Dark.SurfaceTint,
    surfaceContainerLowest = AppColors.Dark.SurfaceContainerLowest,
    surfaceContainerLow = AppColors.Dark.SurfaceContainerLow,
    surfaceContainer = AppColors.Dark.SurfaceContainer,
    surfaceContainerHigh = AppColors.Dark.SurfaceContainerHigh,
    surfaceContainerHighest = AppColors.Dark.SurfaceContainerHighest,
    surfaceBright = AppColors.Dark.SurfaceBright,
    surfaceDim = AppColors.Dark.SurfaceDim,
    outline = AppColors.Dark.Outline,
    outlineVariant = AppColors.Dark.OutlineVariant,
    inverseSurface = AppColors.Dark.InverseSurface,
    inverseOnSurface = AppColors.Dark.InverseOnSurface,
    inversePrimary = AppColors.Dark.InversePrimary,
    scrim = AppColors.Dark.Scrim,
)
