#!/usr/bin/env python3
"""Documentation maintenance tool for MoneySurfer.

Commands:
  index  Generate docs/AI_INDEX.md from AI:SECTION markers.
  toc    Add/update managed Contents blocks in docs/ and ai/ markdown files.
  check  Validate AI sections, generated index, and local markdown links.
  all    Run toc, index, then check.
"""

from __future__ import annotations

import argparse
import dataclasses
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
AI_DIR = ROOT / "ai"
AI_INDEX = DOCS_DIR / "AI_INDEX.md"

SECTION_RE = re.compile(r"<!--\s*AI:SECTION\s+([^>]+?)\s*-->")
END_RE = re.compile(r"<!--\s*AI:END\s*-->")
ATTR_RE = re.compile(r"(\w+)=([^\s]+)")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
HTML_ANCHOR_RE = re.compile(r"<a\s+(?:[^>]*\s+)?(?:id|name)=[\"']([^\"']+)[\"']", re.IGNORECASE)
LINK_RE = re.compile(r"!?\[[^\]]*]\(([^)]+)\)")
TOC_START = "<!-- DOCS:TOC -->"
TOC_END = "<!-- DOCS:END -->"


@dataclasses.dataclass(frozen=True)
class Section:
    section_id: str
    tasks: tuple[str, ...]
    file: Path
    start: int
    end: int
    title: str | None


def rel(path: Path) -> str:
    return path.resolve().relative_to(ROOT).as_posix()


def markdown_files() -> list[Path]:
    files: list[Path] = []
    for base in (DOCS_DIR, AI_DIR):
        if base.exists():
            files.extend(base.rglob("*.md"))
    return sorted(path for path in files if path != AI_INDEX)


def files_for_link_check() -> list[Path]:
    files = markdown_files()
    for path in (
        ROOT / "AGENTS.md",
        ROOT / ".claude" / "CLAUDE.md",
        ROOT / ".github" / "copilot-instructions.md",
    ):
        if path.exists():
            files.append(path)
    return sorted(set(files))


def parse_attrs(raw: str) -> dict[str, str]:
    attrs = dict(ATTR_RE.findall(raw))
    if "id" not in attrs:
        raise ValueError("AI:SECTION missing id")
    return attrs


def first_heading(lines: list[str], start: int, end: int) -> str | None:
    for line in lines[start - 1 : end]:
        match = HEADING_RE.match(line)
        if match:
            return clean_heading(match.group(2))
    return None


def clean_heading(text: str) -> str:
    text = re.sub(r"\s+#+\s*$", "", text.strip())
    text = re.sub(r"\[[^\]]+]\(([^)]+)\)", "", text)
    text = re.sub(r"[`*_~]", "", text)
    return text.strip()


def parse_sections(path: Path) -> list[Section]:
    lines = path.read_text(encoding="utf-8").splitlines()
    sections: list[Section] = []
    current: tuple[dict[str, str], int] | None = None

    for number, line in enumerate(lines, start=1):
        start_match = SECTION_RE.search(line)
        if start_match:
            if current is not None:
                raise ValueError(f"{rel(path)}:{number}: nested AI:SECTION")
            current = (parse_attrs(start_match.group(1)), number)
            continue

        if END_RE.search(line):
            if current is None:
                raise ValueError(f"{rel(path)}:{number}: AI:END without AI:SECTION")
            attrs, start = current
            tasks = tuple(
                task.strip()
                for task in attrs.get("task", "").split(",")
                if task.strip()
            )
            sections.append(
                Section(
                    section_id=attrs["id"],
                    tasks=tasks,
                    file=path,
                    start=start,
                    end=number,
                    title=first_heading(lines, start, number),
                )
            )
            current = None

    if current is not None:
        _, start = current
        raise ValueError(f"{rel(path)}:{start}: AI:SECTION without AI:END")

    return sections


def collect_sections() -> list[Section]:
    sections: list[Section] = []
    seen: dict[str, Path] = {}
    for path in markdown_files():
        for section in parse_sections(path):
            if section.section_id in seen:
                raise ValueError(
                    f"duplicate AI:SECTION id '{section.section_id}' in "
                    f"{rel(seen[section.section_id])} and {rel(path)}"
                )
            seen[section.section_id] = path
            sections.append(section)
    return sorted(sections, key=lambda item: (item.section_id, rel(item.file)))


def render_index(sections: list[Section]) -> str:
    lines = [
        "# AI Index",
        "",
        "> Generated by `python3 scripts/docs_tool.py index`. Do not edit manually.",
        "",
    ]
    for section in sections:
        lines.append(f"## {section.section_id}")
        if section.title:
            lines.append(f"- Title: {section.title}")
        lines.append(f"- File: {rel(section.file)}")
        lines.append(f"- Lines: {section.start}-{section.end}")
        lines.append(f"- Tasks: {', '.join(section.tasks) if section.tasks else '-'}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def command_index(write: bool = True) -> str:
    content = render_index(collect_sections())
    if write:
        AI_INDEX.parent.mkdir(parents=True, exist_ok=True)
        AI_INDEX.write_text(content, encoding="utf-8")
    return content


def slugify(text: str) -> str:
    text = clean_heading(text).lower()
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    text = re.sub(r"\s+", "-", text.strip())
    return text


def headings_from_text(text: str) -> list[tuple[int, str, str]]:
    result: list[tuple[int, str, str]] = []
    for line in text.splitlines():
        match = HEADING_RE.match(line)
        if match:
            level = len(match.group(1))
            title = clean_heading(match.group(2))
            if title and title != "Contents":
                result.append((level, title, slugify(title)))
    return result


def headings(path: Path) -> list[tuple[int, str, str]]:
    return headings_from_text(path.read_text(encoding="utf-8"))


def render_toc(text: str) -> str:
    entries = [(level, title, slug) for level, title, slug in headings_from_text(text) if level <= 3]
    lines = [TOC_START, "## Contents"]
    for level, title, slug in entries:
        indent = "  " * max(level - 2, 0)
        lines.append(f"{indent}- [{title}](#{slug})")
    lines.append(TOC_END)
    return "\n".join(lines)


def remove_existing_toc(text: str) -> str:
    pattern = re.compile(
        rf"\n?{re.escape(TOC_START)}.*?{re.escape(TOC_END)}\n?",
        re.DOTALL,
    )
    return pattern.sub("\n", text).strip() + "\n"


def insert_toc(path: Path) -> bool:
    original = path.read_text(encoding="utf-8")
    without = remove_existing_toc(original)
    lines = without.splitlines()
    toc = render_toc(without)

    insert_at = 0
    if lines and lines[0].startswith("# "):
        insert_at = 1
        while insert_at < len(lines) and lines[insert_at] == "":
            del lines[insert_at]

    new_lines = lines[:insert_at] + ["", toc, ""] + lines[insert_at:]
    updated = "\n".join(new_lines).rstrip() + "\n"
    if updated != original:
        path.write_text(updated, encoding="utf-8")
        return True
    return False


def command_toc() -> int:
    changed = 0
    for path in markdown_files():
        if insert_toc(path):
            changed += 1
    return changed


def anchors_for(path: Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    anchors = {match.group(1) for match in HTML_ANCHOR_RE.finditer(text)}
    counts: dict[str, int] = {}
    for _, _, slug in headings(path):
        if not slug:
            continue
        count = counts.get(slug, 0)
        anchors.add(slug if count == 0 else f"{slug}-{count}")
        counts[slug] = count + 1
    return anchors


def is_external_link(target: str) -> bool:
    parsed = urlparse(target)
    return bool(parsed.scheme and parsed.scheme not in ("", "file"))


def strip_link_title(target: str) -> str:
    target = target.strip()
    if " " in target:
        first, _ = target.split(" ", 1)
        if first.count('"') % 2 == 0:
            return first
    return target


def validate_links(paths: list[Path]) -> list[str]:
    errors: list[str] = []
    anchor_cache: dict[Path, set[str]] = {}
    for path in paths:
        text = path.read_text(encoding="utf-8")
        for line_number, line in enumerate(text.splitlines(), start=1):
            for raw_target in LINK_RE.findall(line):
                target = strip_link_title(raw_target)
                if not target or target.startswith("#"):
                    target_path = path
                    fragment = target[1:]
                else:
                    parsed = urlparse(target)
                    if is_external_link(target) or parsed.scheme == "mailto":
                        continue
                    if target.startswith("file:"):
                        errors.append(f"{rel(path)}:{line_number}: file: links are not allowed: {target}")
                        continue
                    link_path, _, fragment = target.partition("#")
                    if not link_path:
                        target_path = path
                    else:
                        target_path = (path.parent / unquote(link_path)).resolve()

                if not str(target_path).startswith(str(ROOT.resolve())):
                    errors.append(f"{rel(path)}:{line_number}: link escapes repository: {target}")
                    continue
                if not target_path.exists():
                    errors.append(f"{rel(path)}:{line_number}: missing link target: {target}")
                    continue
                if fragment:
                    fragment = unquote(fragment)
                    anchors = anchor_cache.setdefault(target_path, anchors_for(target_path))
                    if fragment not in anchors:
                        errors.append(f"{rel(path)}:{line_number}: missing anchor #{fragment} in {rel(target_path)}")
    return errors


def command_check() -> list[str]:
    errors: list[str] = []
    try:
        expected = command_index(write=False)
    except ValueError as error:
        return [str(error)]

    if not AI_INDEX.exists():
        errors.append("docs/AI_INDEX.md is missing; run `python3 scripts/docs_tool.py index`")
    elif AI_INDEX.read_text(encoding="utf-8") != expected:
        errors.append("docs/AI_INDEX.md is stale; run `python3 scripts/docs_tool.py index`")

    errors.extend(validate_links(files_for_link_check()))
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("index", "toc", "check", "all"))
    args = parser.parse_args()

    if args.command == "index":
        command_index(write=True)
        print(f"Generated {rel(AI_INDEX)}")
        return 0

    if args.command == "toc":
        changed = command_toc()
        print(f"Updated TOC blocks in {changed} files")
        return 0

    if args.command == "check":
        errors = command_check()
        if errors:
            print("\n".join(errors), file=sys.stderr)
            return 1
        print("Documentation checks passed")
        return 0

    changed = command_toc()
    command_index(write=True)
    errors = command_check()
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    print(f"Updated TOC blocks in {changed} files")
    print(f"Generated {rel(AI_INDEX)}")
    print("Documentation checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
