package com.georgeci.moneysurfer.feature.settings.about.licenses

import com.georgeci.moneysurfer.utils.MviViewModel
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import moneysurfer.feature.settings.generated.resources.Res
import org.jetbrains.compose.resources.ExperimentalResourceApi
import org.koin.core.annotation.KoinViewModel

/**
 * Lists the third-party libraries bundled with the app together with their
 * licenses. The data comes from `files/aboutlibraries.json`, generated by the
 * AboutLibraries Gradle plugin (`./gradlew :shared:exportLibraryDefinitions`).
 */
@KoinViewModel
class LicensesViewModel : MviViewModel<LicensesState, LicensesEvent, LicensesEffect>(
    initialState = LicensesState(),
) {

    init {
        loadLicenses()
    }

    override fun onEvent(event: LicensesEvent) {
        when (event) {
            LicensesEvent.OnBackClick -> postSideEffect(LicensesEffect.NavigateBack)
            is LicensesEvent.OnLibraryClick -> updateState {
                copy(expandedLibraryId = if (expandedLibraryId == event.libraryId) null else event.libraryId)
            }
        }
    }

    @OptIn(ExperimentalResourceApi::class)
    private fun loadLicenses() {
        launch(onError = { updateState { copy(isLoading = false, isError = true) } }) {
            val libraries = parseOssLibraries(Res.readBytes(LICENSES_RESOURCE).decodeToString())
            updateState { copy(isLoading = false, libraries = libraries) }
        }
    }

    private companion object {
        const val LICENSES_RESOURCE = "files/aboutlibraries.json"
    }
}

data class LicensesState(
    val isLoading: Boolean = true,
    val isError: Boolean = false,
    val libraries: List<OssLibrary> = emptyList(),
    val expandedLibraryId: String? = null,
)

data class OssLibrary(
    val id: String,
    val name: String,
    val version: String?,
    val author: String?,
    val licenses: List<OssLicense>,
)

data class OssLicense(
    val name: String,
    val content: String?,
)

sealed interface LicensesEvent {
    data object OnBackClick : LicensesEvent
    data class OnLibraryClick(val libraryId: String) : LicensesEvent
}

sealed interface LicensesEffect {
    data object NavigateBack : LicensesEffect
}

/** Maps the AboutLibraries export JSON to the screen model. */
internal fun parseOssLibraries(jsonText: String): List<OssLibrary> {
    val export = exportJson.decodeFromString<AboutLibrariesExport>(jsonText)
    return export.libraries
        .map { library ->
            OssLibrary(
                id = library.uniqueId,
                name = library.name ?: library.uniqueId,
                version = library.artifactVersion,
                author = library.organization?.name
                    ?: library.developers.firstOrNull()?.name,
                licenses = library.licenses.mapNotNull { licenseId ->
                    export.licenses[licenseId]?.let { license ->
                        OssLicense(name = license.name, content = license.content)
                    }
                },
            )
        }
        .sortedBy { it.name.lowercase() }
}

private val exportJson = Json { ignoreUnknownKeys = true }

@Serializable
private data class AboutLibrariesExport(
    val libraries: List<ExportedLibrary> = emptyList(),
    val licenses: Map<String, ExportedLicense> = emptyMap(),
)

@Serializable
private data class ExportedLibrary(
    val uniqueId: String,
    val artifactVersion: String? = null,
    val name: String? = null,
    val developers: List<ExportedDeveloper> = emptyList(),
    val organization: ExportedOrganization? = null,
    val licenses: List<String> = emptyList(),
)

@Serializable
private data class ExportedDeveloper(val name: String? = null)

@Serializable
private data class ExportedOrganization(val name: String? = null)

@Serializable
private data class ExportedLicense(
    val name: String,
    val content: String? = null,
)
